=== sharmilee-sivakumaran/sphinx-documentation-experimental/FN-Scrapers-postgres_insert/scrapers/fn_scrapers/datatypes/international/indonesia/schemas/indonesia_notice.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "International regulation-notice schema",
  "description": "Import schema for int'l reg notices",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "country"
  ],
  "properties": {
    "country": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "notice_id": {
      "type": "string"
    },
    "notice_type": {
      "type": "string"
    },
    "departments": {
      "type": "array",
      "description": "list of sets of departments. Depts with subdepts should be in the same top-level array, and different top-level depts should lead up their own arrays (top of hierarchy)",
      "minItems": 1,
      "items": {
          "type":"object",
          "title": "Notice department schema",
          "required": [
            "department_name",
            "department_hierarchy"
          ],
          "properties": {
            "department_name": {
              "type": "string"
            },
            "department_hierarchy": {
              "type": "integer",
              "description": "index of the heirarchy - used to nest sub-departments arbitrarily deep. Indices shoud be unique in a payload"
            }
          }
      }
    },
    "publication_date": {
      "type": "string",
      "format": "date"
    },
    "publication_name": {
      "type": "string"
    },
    "publication_issue": {
      "type": "string"
    },
    "source_url": {
      "type": "string",
      "format": "uri"
    },
    "document_title": {
      "type": "string"
    },
    "document_id": {
      "type": "integer"
    },
    "download_id": {
      "type": "integer"
    }
  }
}

=== sharmilee-sivakumaran/sphinx-documentation-experimental/FN-Scrapers-postgres_insert/scrapers/fn_scrapers/common/kraken/test_data/canada_input.json
{
    "document_title": "Income Tax Act : Revocation of registration of charities",
    "download_id": 2138615,
    "publication_name": "Canada Gazette",
    "title": "Income Tax Act : Revocation of registration of charities",
    "country": "Canada",
    "publication_issue": " Part I: Volume 152,Edition No. 17",
    "departments": [
        {
            "department_hierarchy": 0,
            "department_name": "Canada Revenue Agency"
        }
    ],
    "source_url": "http://gazette.gc.ca/rp-pr/p1/2018/2018-04-28/html/index-eng.html",
    "notice_type": "Notice or Proposed Rule",
    "publication_date": "2018-04-28",
    "document_id": 1800883
}
